In [1]:
### Data cleaning and Normalization (scalling the numerical data to particular range,typically between 0 and 1)
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('sample_data.csv')

In [3]:
df.head()

   Name      Age    Salary     Department
0  Alice     25.0   50000.0            HR
1  Bob       30.0             Engineering
2  Charlie   35.0   70000.0   Engineering
3  David            60000.0            HR
4  Eve       28.0   80000.0            HR

In [4]:
print("No of missing value = ")
print(df.isnull().sum(axis=0)) # zero

No of missing value =
Name           0
 Age           0
 Salary        0
 Department    0
dtype: int64

In [5]:
df.head(10)

   Name      Age    Salary     Department
0  Alice     25.0   50000.0            HR
1  Bob       30.0             Engineering
2  Charlie   35.0   70000.0   Engineering
3  David            60000.0            HR
4  Eve       28.0   80000.0            HR
5  Frank     40.0   55000.0         Sales
6  Grace     50.0   85000.0         Sales
7  Hank      60.0   90000.0         Sales

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         8 non-null      object
 1    Age         8 non-null      object
 2    Salary      8 non-null      object
 3    Department  8 non-null      object
dtypes: object(4)
memory usage: 388.0+ bytes

In [7]:
import string

alphabet_list = list(string.ascii_lowercase) + list(string.ascii_uppercase)
print(alphabet_list)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

In [8]:
import random
##Shuffling the alphabet-list
random.shuffle(alphabet_list)

In [9]:
new_ent = dict()
# Generate a list of departments
departments = ['HR', 'Finance', 'Engineering', 'Marketing', 'Sales', 'IT', 'Operations', 'Legal', 'R&D', 'Support']

for cols in df.columns.map(lambda x:x.strip()).to_list():
    new_ent[cols] = []
    for i in range(100):
        if cols == 'Name':
            string = ""
            for j in range(4):
                string += random.choice(alphabet_list)
        
            new_ent['Name'].append(string)
        elif cols == 'Age':
            new_ent[cols].append(random.randint(20,100))

        elif cols == "Department":
            new_ent[cols].append(random.choice(departments))
        
        elif cols == "Salary":
            new_ent[cols].append(float(random.randrange(20000,100000,5000)))

print(new_ent)

{'Name': ['nxlK', 'NzJv', 'gBcA', 'DtqA', 'QLLV', 'cIau', 'FJyx', 'xOMz', 'FvUC', 'cujL', 'SgQF', 'OOEs', 'YFRl', 'aRJA', 'PwbS', 'MuiF', 'FPKK', 'mONZ', 'uBHs', 'TKYF', 'KWFU', 'Tpym', 'ZcbA', 'GNsr', 'KJMp', 'LqPk', 'IOpW', 'JERv', 'dSJF', 'OBsE', 'FekD', 'sILl', 'kOxg', 'SRaC', 'drMc', 'mupe', 'VrKv', 'ikaf', 'bwpz', 'ucHx', 'mQzY', 'uIzG', 'gbRw', 'omry', 'whSU', 'aawJ', 'qopL', 'KFbz', 'JPPm', 'kJHN', 'QoQA', 'tivE', 'nlSq', 'mdbU', 'iTjR', 'wnSt', 'XoOx', 'HvoA', 'YEYn', 'anwW', 'wwuV', 'OOUp', 'jKVJ', 'clug', 'CkfB', 'Dzxi', 'CgzX', 'mzNJ', 'GSJz', 'PCrV', 'cpyG', 'ZbvV', 'ZHoO', 'QFGK', 'oSue', 'eKCk', 'rrXk', 'Dloo', 'YJWe', 'obeu', 'vtKL', 'KVgL', 'RxzT', 'XHXS', 'pzCd', 'gsuM', 'PXar', 'dhbE', 'WHcp', 'opmD', 'OCMY', 'dXHc', 'PnJe', 'tjHc', 'iVEH', 'rDrH', 'YBmJ', 'cCEN', 'kQbI', 'tSRu'], 'Age': [47, 21, 52, 46, 53, 33, 46, 78, 97, 52, 68, 57, 38, 78, 67, 33, 57, 48, 52, 61, 49, 75, 44, 47, 37, 99, 30, 86, 69, 80, 27, 96, 54, 48, 29, 92, 47, 93, 37, 86, 27, 91, 26, 57, 77, 78, 50, 28, 87, 33, 26, 65, 80, 55, 88, 46, 43, 62, 28, 28, 21, 57, 69, 38, 49, 92, 31, 29, 54, 34, 68, 67, 49, 26, 98, 50, 92, 96, 47, 25, 28, 72, 59, 84, 30, 22, 72, 24, 62, 66, 31, 26, 63, 31, 37, 56, 81, 34, 38, 29], 'Salary': [45000.0, 60000.0, 75000.0, 55000.0, 60000.0, 20000.0, 55000.0, 75000.0, 85000.0, 65000.0, 70000.0, 40000.0, 30000.0, 40000.0, 55000.0, 90000.0, 95000.0, 50000.0, 50000.0, 50000.0, 35000.0, 40000.0, 20000.0, 40000.0, 50000.0, 40000.0, 50000.0, 70000.0, 35000.0, 70000.0, 65000.0, 90000.0, 25000.0, 30000.0, 65000.0, 90000.0, 70000.0, 70000.0, 60000.0, 25000.0, 65000.0, 85000.0, 75000.0, 60000.0, 20000.0, 25000.0, 20000.0, 70000.0, 80000.0, 60000.0, 35000.0, 35000.0, 75000.0, 70000.0, 75000.0, 80000.0, 40000.0, 75000.0, 85000.0, 70000.0, 85000.0, 45000.0, 65000.0, 45000.0, 95000.0, 85000.0, 80000.0, 30000.0, 80000.0, 85000.0, 55000.0, 30000.0, 55000.0, 30000.0, 80000.0, 70000.0, 70000.0, 85000.0, 75000.0, 65000.0, 75000.0, 20000.0, 80000.0, 45000.0, 50000.0, 90000.0, 30000.0, 70000.0, 35000.0, 60000.0, 55000.0, 70000.0, 55000.0, 70000.0, 35000.0, 50000.0, 70000.0, 90000.0, 75000.0, 85000.0], 'Department': ['Marketing', 'Legal', 'Marketing', 'Finance', 'Sales', 'IT', 'Engineering', 'Finance', 'Sales', 'Finance', 'R&D', 'Engineering', 'Marketing', 'Marketing', 'Engineering', 'Marketing', 'Engineering', 'Sales', 'Engineering', 'R&D', 'Support', 'Marketing', 'IT', 'HR', 'Marketing', 'Support', 'HR', 'HR', 'IT', 'Legal', 'Finance', 'HR', 'Engineering', 'Support', 'Marketing', 'Operations', 'Legal', 'Support', 'Support', 'Support', 'Support', 'Operations', 'Engineering', 'HR', 'Finance', 'Engineering', 'Support', 'Legal', 'Engineering', 'Legal', 'IT', 'Sales', 'IT', 'Operations', 'IT', 'Operations', 'HR', 'Legal', 'IT', 'R&D', 'Legal', 'HR', 'Sales', 'IT', 'Sales', 'Finance', 'HR', 'Finance', 'Marketing', 'Sales', 'R&D', 'Engineering', 'HR', 'Operations', 'Finance', 'HR', 'IT', 'HR', 'HR', 'Legal', 'Sales', 'Legal', 'Legal', 'Legal', 'Engineering', 'HR', 'Sales', 'R&D', 'IT', 'Finance', 'R&D', 'Finance', 'Support', 'Support', 'Legal', 'Finance', 'HR', 'Legal', 'Legal', 'R&D']}

In [10]:
df.columns = df.columns.map(lambda s:s.strip()).to_list()
new_df = pd.DataFrame(new_ent)
for i in range(5):
    cols = random.choice(new_df.columns)
    #choosing value
    index = random.randrange(0,len(new_df[cols]))
    new_df.loc[index,cols] = np.nan
    #putting nA there


# df.add(new_ent)
print(new_df.isna().sum())
print(new_df.to_string())

Name          2
Age           1
Salary        1
Department    1
dtype: int64
    Name   Age   Salary   Department
0   nxlK  47.0  45000.0    Marketing
1   NzJv  21.0  60000.0        Legal
2   gBcA  52.0  75000.0    Marketing
3   DtqA  46.0  55000.0      Finance
4   QLLV  53.0  60000.0        Sales
5   cIau  33.0  20000.0           IT
6   FJyx  46.0  55000.0  Engineering
7   xOMz  78.0  75000.0      Finance
8   FvUC  97.0  85000.0        Sales
9   cujL  52.0      NaN      Finance
10   NaN  68.0  70000.0          R&D
11  OOEs  57.0  40000.0  Engineering
12  YFRl  38.0  30000.0    Marketing
13  aRJA  78.0  40000.0    Marketing
14  PwbS  67.0  55000.0  Engineering
15  MuiF  33.0  90000.0    Marketing
16  FPKK  57.0  95000.0  Engineering
17  mONZ  48.0  50000.0        Sales
18  uBHs  52.0  50000.0  Engineering
19  TKYF  61.0  50000.0          R&D
20  KWFU  49.0  35000.0      Support
21  Tpym  75.0  40000.0    Marketing
22  ZcbA  44.0  20000.0           IT
23  GNsr  47.0  40000.0           HR
24  KJMp  37.0  50000.0    Marketing
25  LqPk  99.0  40000.0      Support
26  IOpW  30.0  50000.0           HR
27  JERv  86.0  70000.0           HR
28  dSJF  69.0  35000.0           IT
29  OBsE  80.0  70000.0        Legal
30  FekD  27.0  65000.0      Finance
31  sILl  96.0  90000.0           HR
32  kOxg  54.0  25000.0  Engineering
33  SRaC  48.0  30000.0      Support
34  drMc  29.0  65000.0    Marketing
35  mupe  92.0  90000.0   Operations
36  VrKv  47.0  70000.0        Legal
37  ikaf  93.0  70000.0      Support
38  bwpz  37.0  60000.0      Support
39  ucHx  86.0  25000.0      Support
40  mQzY  27.0  65000.0      Support
41  uIzG  91.0  85000.0   Operations
42  gbRw  26.0  75000.0  Engineering
43  omry  57.0  60000.0           HR
44  whSU  77.0  20000.0      Finance
45  aawJ  78.0  25000.0  Engineering
46  qopL  50.0  20000.0      Support
47  KFbz  28.0  70000.0        Legal
48  JPPm  87.0  80000.0  Engineering
49  kJHN  33.0  60000.0        Legal
50  QoQA  26.0  35000.0          NaN
51  tivE  65.0  35000.0        Sales
52  nlSq  80.0  75000.0           IT
53  mdbU  55.0  70000.0   Operations
54  iTjR  88.0  75000.0           IT
55  wnSt  46.0  80000.0   Operations
56  XoOx  43.0  40000.0           HR
57  HvoA  62.0  75000.0        Legal
58  YEYn  28.0  85000.0           IT
59  anwW  28.0  70000.0          R&D
60  wwuV  21.0  85000.0        Legal
61  OOUp  57.0  45000.0           HR
62  jKVJ  69.0  65000.0        Sales
63  clug  38.0  45000.0           IT
64  CkfB  49.0  95000.0        Sales
65  Dzxi  92.0  85000.0      Finance
66  CgzX  31.0  80000.0           HR
67  mzNJ  29.0  30000.0      Finance
68  GSJz  54.0  80000.0    Marketing
69  PCrV  34.0  85000.0        Sales
70  cpyG  68.0  55000.0          R&D
71  ZbvV  67.0  30000.0  Engineering
72  ZHoO  49.0  55000.0           HR
73  QFGK  26.0  30000.0   Operations
74  oSue  98.0  80000.0      Finance
75  eKCk  50.0  70000.0           HR
76  rrXk  92.0  70000.0           IT
77  Dloo  96.0  85000.0           HR
78   NaN  47.0  75000.0           HR
79  obeu  25.0  65000.0        Legal
80  vtKL  28.0  75000.0        Sales
81  KVgL  72.0  20000.0        Legal
82  RxzT  59.0  80000.0        Legal
83  XHXS  84.0  45000.0        Legal
84  pzCd  30.0  50000.0  Engineering
85  gsuM  22.0  90000.0           HR
86  PXar  72.0  30000.0        Sales
87  dhbE  24.0  70000.0          R&D
88  WHcp  62.0  35000.0           IT
89  opmD  66.0  60000.0      Finance
90  OCMY  31.0  55000.0          R&D
91  dXHc  26.0  70000.0      Finance
92  PnJe  63.0  55000.0      Support
93  tjHc  31.0  70000.0      Support
94  iVEH   NaN  35000.0        Legal
95  rDrH  56.0  50000.0      Finance
96  YBmJ  81.0  70000.0           HR
97  cCEN  34.0  90000.0        Legal
98  kQbI  38.0  75000.0        Legal
99  tSRu  29.0  85000.0          R&D

In [11]:
# concatinating to our existing df

In [12]:
updated_df = pd.concat([df,new_df],axis=0)

print(updated_df)

       Name    Age    Salary    Department
0   Alice     25.0   50000.0            HR
1   Bob       30.0             Engineering
2   Charlie   35.0   70000.0   Engineering
3   David            60000.0            HR
4   Eve       28.0   80000.0            HR
..      ...    ...       ...           ...
95     rDrH   56.0   50000.0       Finance
96     YBmJ   81.0   70000.0            HR
97     cCEN   34.0   90000.0         Legal
98     kQbI   38.0   75000.0         Legal
99     tSRu   29.0   85000.0           R&D

[108 rows x 4 columns]

In [13]:
print("After adding some missing values the new df looks like")

print("count odf missing values = ",updated_df.isna().sum(),end="\n")
print("counting the non missing values = \n",updated_df.count())
print("---------------- info on dataframe--------------")

After adding some missing values the new df looks like
count odf missing values =  Name          2
Age           1
Salary        1
Department    1
dtype: int64
counting the non missing values =
 Name          106
Age           107
Salary        107
Department    107
dtype: int64
---------------- info on dataframe--------------

In [14]:
updated_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 108 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        106 non-null    object
 1   Age         107 non-null    object
 2   Salary      107 non-null    object
 3   Department  107 non-null    object
dtypes: object(4)
memory usage: 4.2+ KB

In [15]:
updated_df.describe()

           Name    Age   Salary Department
count       106  107.0    107.0        107
unique      106   61.0     24.0         13
top     Alice     47.0  70000.0      Legal
freq          1    4.0     14.0         14

In [16]:
#removing the null values and resetting the index
updated_df2 = updated_df.dropna().reset_index(drop=True)

In [17]:
print(updated_df2.to_string())

updated_df2.tail(100)

        Name    Age    Salary    Department
0    Alice     25.0   50000.0            HR
1    Bob       30.0             Engineering
2    Charlie   35.0   70000.0   Engineering
3    David            60000.0            HR
4    Eve       28.0   80000.0            HR
5    Frank     40.0   55000.0         Sales
6    Grace     50.0   85000.0         Sales
7    Hank      60.0   90000.0         Sales
8       nxlK   47.0   45000.0     Marketing
9       NzJv   21.0   60000.0         Legal
10      gBcA   52.0   75000.0     Marketing
11      DtqA   46.0   55000.0       Finance
12      QLLV   53.0   60000.0         Sales
13      cIau   33.0   20000.0            IT
14      FJyx   46.0   55000.0   Engineering
15      xOMz   78.0   75000.0       Finance
16      FvUC   97.0   85000.0         Sales
17      OOEs   57.0   40000.0   Engineering
18      YFRl   38.0   30000.0     Marketing
19      aRJA   78.0   40000.0     Marketing
20      PwbS   67.0   55000.0   Engineering
21      MuiF   33.0   90000.0     Marketing
22      FPKK   57.0   95000.0   Engineering
23      mONZ   48.0   50000.0         Sales
24      uBHs   52.0   50000.0   Engineering
25      TKYF   61.0   50000.0           R&D
26      KWFU   49.0   35000.0       Support
27      Tpym   75.0   40000.0     Marketing
28      ZcbA   44.0   20000.0            IT
29      GNsr   47.0   40000.0            HR
30      KJMp   37.0   50000.0     Marketing
31      LqPk   99.0   40000.0       Support
32      IOpW   30.0   50000.0            HR
33      JERv   86.0   70000.0            HR
34      dSJF   69.0   35000.0            IT
35      OBsE   80.0   70000.0         Legal
36      FekD   27.0   65000.0       Finance
37      sILl   96.0   90000.0            HR
38      kOxg   54.0   25000.0   Engineering
39      SRaC   48.0   30000.0       Support
40      drMc   29.0   65000.0     Marketing
41      mupe   92.0   90000.0    Operations
42      VrKv   47.0   70000.0         Legal
43      ikaf   93.0   70000.0       Support
44      bwpz   37.0   60000.0       Support
45      ucHx   86.0   25000.0       Support
46      mQzY   27.0   65000.0       Support
47      uIzG   91.0   85000.0    Operations
48      gbRw   26.0   75000.0   Engineering
49      omry   57.0   60000.0            HR
50      whSU   77.0   20000.0       Finance
51      aawJ   78.0   25000.0   Engineering
52      qopL   50.0   20000.0       Support
53      KFbz   28.0   70000.0         Legal
54      JPPm   87.0   80000.0   Engineering
55      kJHN   33.0   60000.0         Legal
56      tivE   65.0   35000.0         Sales
57      nlSq   80.0   75000.0            IT
58      mdbU   55.0   70000.0    Operations
59      iTjR   88.0   75000.0            IT
60      wnSt   46.0   80000.0    Operations
61      XoOx   43.0   40000.0            HR
62      HvoA   62.0   75000.0         Legal
63      YEYn   28.0   85000.0            IT
64      anwW   28.0   70000.0           R&D
65      wwuV   21.0   85000.0         Legal
66      OOUp   57.0   45000.0            HR
67      jKVJ   69.0   65000.0         Sales
68      clug   38.0   45000.0            IT
69      CkfB   49.0   95000.0         Sales
70      Dzxi   92.0   85000.0       Finance
71      CgzX   31.0   80000.0            HR
72      mzNJ   29.0   30000.0       Finance
73      GSJz   54.0   80000.0     Marketing
74      PCrV   34.0   85000.0         Sales
75      cpyG   68.0   55000.0           R&D
76      ZbvV   67.0   30000.0   Engineering
77      ZHoO   49.0   55000.0            HR
78      QFGK   26.0   30000.0    Operations
79      oSue   98.0   80000.0       Finance
80      eKCk   50.0   70000.0            HR
81      rrXk   92.0   70000.0            IT
82      Dloo   96.0   85000.0            HR
83      obeu   25.0   65000.0         Legal
84      vtKL   28.0   75000.0         Sales
85      KVgL   72.0   20000.0         Legal
86      RxzT   59.0   80000.0         Legal
87      XHXS   84.0   45000.0         Legal
88      pzCd   30.0   50000.0   Engineering
89      gsuM   22.0   90000.0            HR
90      PXar   72.0   30000.0         Sales
91      dhbE   24.0   70000.0           R&D
92      WHcp   62.0   35000.0            IT
93      opmD   66.0   60000.0       Finance
94      OCMY   31.0   55000.0           R&D
95      dXHc   26.0   70000.0       Finance
96      PnJe   63.0   55000.0       Support
97      tjHc   31.0   70000.0       Support
98      rDrH   56.0   50000.0       Finance
99      YBmJ   81.0   70000.0            HR
100     cCEN   34.0   90000.0         Legal
101     kQbI   38.0   75000.0         Legal
102     tSRu   29.0   85000.0           R&D

        Name    Age    Salary Department
3    David            60000.0         HR
4    Eve       28.0   80000.0         HR
5    Frank     40.0   55000.0      Sales
6    Grace     50.0   85000.0      Sales
7    Hank      60.0   90000.0      Sales
..       ...    ...       ...        ...
98      rDrH   56.0   50000.0    Finance
99      YBmJ   81.0   70000.0         HR
100     cCEN   34.0   90000.0      Legal
101     kQbI   38.0   75000.0      Legal
102     tSRu   29.0   85000.0        R&D

[100 rows x 4 columns]

In [18]:
updated_df['Age'] = pd.to_numeric(updated_df['Age'],errors='coerce',downcast='float')
updated_df['Salary'] = pd.to_numeric(updated_df['Salary'],errors='coerce',downcast='float')

In [19]:
updated_df3 = updated_df.fillna({
    "Age":np.round(updated_df['Age'].mean()), # type: ignore
    "Salary":np.round(updated_df['Salary'].mean()) # type: ignore
})
## droping the missing rows
updated_df3['Name'].dropna(inplace=True)
updated_df3['Department'].dropna(inplace=True)
# filling na values with the mean of the data

In [20]:
# updated_df3

In [21]:
# Set pandas display precision to 2 decimal points
pd.set_option('display.precision', 2)
# Now, displaying the DataFrame will show numbers with 2 decimal places
updated_df3.head(10)

      Name   Age   Salary    Department
0  Alice    25.0  50000.0            HR
1  Bob      30.0  59906.0   Engineering
2  Charlie  35.0  70000.0   Engineering
3  David    53.0  60000.0            HR
4  Eve      28.0  80000.0            HR
5  Frank    40.0  55000.0         Sales
6  Grace    50.0  85000.0         Sales
7  Hank     60.0  90000.0         Sales
0     nxlK  47.0  45000.0     Marketing
1     NzJv  21.0  60000.0         Legal

In [22]:
updated_df3.describe()

          Age    Salary
count  108.00    108.00
mean    53.31  59905.67
std     22.20  20518.75
min     21.00  20000.00
25%     33.00  45000.00
50%     50.00  60000.00
75%     68.25  75000.00
max     99.00  95000.00

**Forward fill** and **backward fill** are techniques used to handle missing data in a DataFrame:

- **Forward fill (`ffill`)**: This method propagates the last valid observation forward to fill missing values. For example, if a value is missing, it will be replaced by the previous non-missing value in the column.
- **Backward fill (`bfill`)**: This method uses the next valid observation to fill missing values. If a value is missing, it will be replaced by the next non-missing value in the column.

These methods are commonly used with `pandas.DataFrame.fillna(method='ffill')` or `pandas.DataFrame.fillna(method='bfill')`.

In [23]:
updated_df3.head(10)

      Name   Age   Salary    Department
0  Alice    25.0  50000.0            HR
1  Bob      30.0  59906.0   Engineering
2  Charlie  35.0  70000.0   Engineering
3  David    53.0  60000.0            HR
4  Eve      28.0  80000.0            HR
5  Frank    40.0  55000.0         Sales
6  Grace    50.0  85000.0         Sales
7  Hank     60.0  90000.0         Sales
0     nxlK  47.0  45000.0     Marketing
1     NzJv  21.0  60000.0         Legal

In [24]:
#adding duplicates
print(updated_df3.iloc[1]['Age'])

updated_df3 = pd.concat([updated_df3,updated_df3.iloc[[22]],updated_df3.iloc[[1]]],ignore_index=True)

30.0

In [25]:
print(updated_df3['Department'].values)

[' HR' ' Engineering' ' Engineering' ' HR' ' HR' ' Sales' ' Sales'
 ' Sales' 'Marketing' 'Legal' 'Marketing' 'Finance' 'Sales' 'IT'
 'Engineering' 'Finance' 'Sales' 'Finance' 'R&D' 'Engineering' 'Marketing'
 'Marketing' 'Engineering' 'Marketing' 'Engineering' 'Sales' 'Engineering'
 'R&D' 'Support' 'Marketing' 'IT' 'HR' 'Marketing' 'Support' 'HR' 'HR'
 'IT' 'Legal' 'Finance' 'HR' 'Engineering' 'Support' 'Marketing'
 'Operations' 'Legal' 'Support' 'Support' 'Support' 'Support' 'Operations'
 'Engineering' 'HR' 'Finance' 'Engineering' 'Support' 'Legal'
 'Engineering' 'Legal' nan 'Sales' 'IT' 'Operations' 'IT' 'Operations'
 'HR' 'Legal' 'IT' 'R&D' 'Legal' 'HR' 'Sales' 'IT' 'Sales' 'Finance' 'HR'
 'Finance' 'Marketing' 'Sales' 'R&D' 'Engineering' 'HR' 'Operations'
 'Finance' 'HR' 'IT' 'HR' 'HR' 'Legal' 'Sales' 'Legal' 'Legal' 'Legal'
 'Engineering' 'HR' 'Sales' 'R&D' 'IT' 'Finance' 'R&D' 'Finance' 'Support'
 'Support' 'Legal' 'Finance' 'HR' 'Legal' 'Legal' 'R&D' 'Engineering'
 ' Engineering']

In [26]:
# dropping duplicates
print("Before dropping duplicates the shape of df = ",updated_df3.shape)
print("Before dropping duplicates the size = ",updated_df3.size)
updated_df3.drop_duplicates(inplace=True)
print("after dropping duplicates the shape of df = ",updated_df3.shape)

Before dropping duplicates the shape of df =  (110, 4)
Before dropping duplicates the size =  440
after dropping duplicates the shape of df =  (108, 4)

In [27]:
#replacing the Departments with full name

updated_df3.replace({"Department":{v:" ".join([v,"Dept"]) for v in updated_df3['Department'].values
                                                 }},inplace=True)

TypeError: sequence item 0: expected str instance, float found

In [ ]:
#### most = updated dataframe

updated_df3

        Name   Age   Salary         Department
0    Alice    25.0  50000.0            HR Dept
1    Bob      30.0  61745.0   Engineering Dept
2    Charlie  35.0  70000.0   Engineering Dept
3    David    60.0  60000.0            HR Dept
4    Eve      28.0  80000.0            HR Dept
..       ...   ...      ...                ...
103     JEaJ  44.0  95000.0            IT Dept
104     RyYo  81.0  75000.0           R&D Dept
105     mVuu  95.0  40000.0            HR Dept
106     KJmU  97.0  55000.0   Engineering Dept
107     nxnl  27.0  50000.0         Legal Dept

[108 rows x 4 columns]

In [ ]:
import tabulate

In [ ]:
updated_df3.corr(numeric_only=True)

         Age  Salary
Age     1.00   -0.13
Salary -0.13    1.00

In [ ]:

print(tabulate.tabulate(updated_df3.corr(numeric_only=True),headers='keys',tablefmt='grid',floatfmt=".2f",numalign='right'))

+--------+-------+----------+
|        |   Age |   Salary |
+========+=======+==========+
| Age    |  1.00 |    -0.13 |
+--------+-------+----------+
| Salary | -0.13 |     1.00 |
+--------+-------+----------+

In [30]:
# ------------------------------------- Normalizing the age, and salary ---------------------------------
from sklearn.preprocessing import MinMaxScaler

min_max_scalar = MinMaxScaler()
updated_df3['Salary'] = min_max_scalar.fit_transform(updated_df3[['Salary']])
print(updated_df3)

        Name   Age  Salary    Department
0    Alice    25.0    0.40            HR
1    Bob      30.0    0.53   Engineering
2    Charlie  35.0    0.67   Engineering
3    David    53.0    0.53            HR
4    Eve      28.0    0.80            HR
..       ...   ...     ...           ...
103     rDrH  56.0    0.40       Finance
104     YBmJ  81.0    0.67            HR
105     cCEN  34.0    0.93         Legal
106     kQbI  38.0    0.73         Legal
107     tSRu  29.0    0.87           R&D

[108 rows x 4 columns]